// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Article: typeof import('./src/components/article/Article.vue')['default']
    Article_nav: typeof import('./src/components/article/Article_nav.vue')['default']
    Default_button: typeof import('./src/components/elements/Default_button.vue')['default']
    Default_icon: typeof import('./src/components/elements/Default_icon.vue')['default']
    Fields: typeof import('./src/components/tech/Fields.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/header/Header.vue')['default']
    HeaderLink: typeof import('./src/components/header/HeaderLink.vue')['default']
    LangFields: typeof import('./src/components/tech/LangFields.vue')['default']
    Language: typeof import('./src/components/tech/Language.vue')['default']
    Links: typeof import('./src/components/Links.vue')['default']
    Loader: typeof import('./src/components/Loader.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    Sidebar: typeof import('./src/components/sidebar/Sidebar.vue')['default']
    Sidebar_right: typeof import('./src/components/sidebar/Sidebar_right.vue')['default']
    Start: typeof import('./src/components/Start.vue')['default']
  }
}

export { }
